eTickets/Controllers/ActorsController.cs
using eTickets.Data;
using eTickets.Data.Base.BaesInterFaces;
using eTickets.Data.Services;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ActorsController : Controller
    {
        private readonly IunitOfWork _unitOfWork;
        public ActorsController(IunitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _unitOfWork.ActorService.GetAllAsync();
            return View(data);
        }

        //Actors/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);

            }
            await _unitOfWork.ActorService.AddAsync(actor);
            await _unitOfWork.Complete();
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]

        public async Task<IActionResult> Details(int id)
        {
            var atorDetails = await _unitOfWork.ActorService.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            return View(atorDetails);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var atorDetails = await _unitOfWork.ActorService.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            return View(atorDetails);
        }
        [HttpPost]

        public async Task<IActionResult> Edit(int id, Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);

            }
            await _unitOfWork.ActorService.UpdateAsync(id, actor);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var atorDetails = await _unitOfWork.ActorService.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            return View(atorDetails);
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var atorDetails = await _unitOfWork.ActorService.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            await _unitOfWork.ActorService.DeleteAsync(id);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }




    }
}

eTickets/Controllers/CinemasController.cs
using eTickets.Data;
using eTickets.Data.Base.BaesInterFaces;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CinemasController : Controller
    {
        private readonly IunitOfWork _unitOfWork;

        ///private readonly AppDbContext _context;
        ///public CinemasController(AppDbContext context)
        ///{
        ///    _context = context;
        ///}

        public CinemasController(IunitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [AllowAnonymous]

        public async Task<IActionResult> Index()
        {
            var allCinemas = await _unitOfWork.CinemasServices.GetAllAsync();
            return View(allCinemas);
        }


        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create([Bind("Name,Logo,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);

            }
            await _unitOfWork.CinemasServices.AddAsync(cinema);
            await _unitOfWork.Complete();
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]

        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _unitOfWork.CinemasServices.GetByIdAsync(id);
            if (producerDetails is null)
                return View("NotFound");
            return View(producerDetails);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var atorDetails = await _unitOfWork.CinemasServices.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            return View(atorDetails);
        }
        [HttpPost]

        public async Task<IActionResult> Edit(int id, Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);

            }
            await _unitOfWork.CinemasServices.UpdateAsync(id, cinema);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var atorDetails = await _unitOfWork.CinemasServices.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            return View(atorDetails);
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var atorDetails = await _unitOfWork.CinemasServices.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            await _unitOfWork.CinemasServices.DeleteAsync(id);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

    }
}

eTickets/Controllers/MoviesController.cs
using eTickets.Data;
using eTickets.Data.Base.BaesInterFaces;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        private readonly IunitOfWork _unitOfWork;

        ///private readonly AppDbContext _context;
        ///public MoviesController(AppDbContext context)
        ///{
        ///    _context = context;
        ///}

        public MoviesController(IunitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [AllowAnonymous]

        public async Task<IActionResult> Index()
        {
            var allMovies = await _unitOfWork.MoviesServices.GetAllAsync(n => n.Cinema);
            return View(allMovies);
        }
        //Filter
        [AllowAnonymous]

        public async Task<IActionResult> Filter( string searchString)
        {
            var allMovies = await _unitOfWork.MoviesServices.GetAllAsync(n => n.Cinema);
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allMovies.Where(n=> n.Name.ToLower() .Contains(searchString.ToLower())|| n.Description.ToLower().Contains(searchString.ToLower() ))
                    .ToList();
                return View(nameof(Index), filteredResult);
            }
            return View( nameof(Index), allMovies);
        }
        [AllowAnonymous]

        public async Task<IActionResult> Details(int id)
        {
            var movieDetails = await _unitOfWork.MoviesServices.GetMovieByIdAsync(id);

            return View(movieDetails);
        }


        public async Task<IActionResult> Create()
        {

            var movieDropDownsData = await _unitOfWork.MoviesServices.GetNewMovieDropdownsValues();
            ViewBag.Cinmeas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropDownsData = await _unitOfWork.MoviesServices.GetNewMovieDropdownsValues();
                ViewBag.Cinmeas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
                return View(movie);
            }
            await _unitOfWork.MoviesServices.AddNewMovieAsync(movie);

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Edit(int id)
        {

            var movieDetails = await _unitOfWork.MoviesServices.GetMovieByIdAsync(id);
            if (movieDetails == null) return View("NotFound");
             var responce = new NewMovieVM()
            {
                Id = id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                ImageURL = movieDetails.ImageURL,
                MoiveCategory = movieDetails.MoiveCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerID = movieDetails.ProducerID,
                ActorsIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList()
            };
            var movieDropDownsData = await _unitOfWork.MoviesServices.GetNewMovieDropdownsValues();
            ViewBag.Cinmeas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
            return View(responce);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id ,  NewMovieVM movie)
        {
            if(id != movie.Id) return View(nameof(NotFound));
            if (!ModelState.IsValid)
            {
                var movieDropDownsData = await _unitOfWork.MoviesServices.GetNewMovieDropdownsValues();
                ViewBag.Cinmeas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
                return View(movie);
            }
            await _unitOfWork.MoviesServices.UpdateMovieAsync(movie);

            return RedirectToAction(nameof(Index));
        }

    }
}

eTickets/Controllers/ProducersController.cs
using eTickets.Data;
using eTickets.Data.Base.BaesInterFaces;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles =UserRoles.Admin)]
    public class ProducersController : Controller
    {
        private readonly IunitOfWork _unitOfWork;

        public ProducersController(IunitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        [AllowAnonymous]

        public async Task<IActionResult> Index()
        {
            var AllProducers = await _unitOfWork.ProducerServices.GetAllAsync();
            return View(AllProducers);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);

            }
            await _unitOfWork.ProducerServices.AddAsync(producer);
            await _unitOfWork.Complete();
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]

        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _unitOfWork.ProducerServices.GetByIdAsync(id);
            if (producerDetails is null)
                return View("NotFound");
            return View(producerDetails);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _unitOfWork.ProducerServices.GetByIdAsync(id);
            if (producerDetails is null)
                return View("NotFound");
            return View(producerDetails);
        }
        [HttpPost]

        public async Task<IActionResult> Edit(int id, Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);

            }
            await _unitOfWork.ProducerServices.UpdateAsync(id, producer);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var producerDetails = await _unitOfWork.ProducerServices.GetByIdAsync(id);
            if (producerDetails is null)
                return View("NotFound");
            return View(producerDetails);
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetails = await _unitOfWork.ProducerServices.GetByIdAsync(id);
            if (producerDetails is null)
                return View("NotFound");
            await _unitOfWork.ProducerServices.DeleteAsync(id);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

    }
}

eTickets/Views/Shared/NotFound.cshtml
<div class="row text-center ">
    <div class="col-md-6 offset-3">

    <h1 class="text-info ">you have reached the end of the internet</h1>
    <hr/>
    <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index" >Home Page</a>
    </div>
    
</div>

eTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index"><i class="fas fa-film"></i> Movies</a>
                        </li>

                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="fa-solid fa-video"></i> Cinemas</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="fas fa-headset"></i> Producers</a>
                                    <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="fa-solid fa-user"></i> Actors</a>
                                </div>
                            </li>

                        }


                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                    </form>

                    <ul class="navbar-nav ">
                        @await Component.InvokeAsync("ShoppingCartSummary")

                    </ul>
                    <partial name="partialviews\_identity.cshtml" />
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy 2023 - eTickets - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>