eTickets/Controllers/ActorsController.cs
using eTickets.Data;
using eTickets.Data.Base.BaesInterFaces;
using eTickets.Data.Services;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ActorsController : Controller
    {
        private readonly IunitOfWork _unitOfWork;
        public ActorsController(IunitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _unitOfWork.ActorService.GetAllAsync();
            return View(data);
        }

        //Actors/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);

            }
            await _unitOfWork.ActorService.AddAsync(actor);
            await _unitOfWork.Complete();
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]

        public async Task<IActionResult> Details(int id)
        {
            var atorDetails = await _unitOfWork.ActorService.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            return View(atorDetails);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var atorDetails = await _unitOfWork.ActorService.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            return View(atorDetails);
        }
        [HttpPost]

        public async Task<IActionResult> Edit(int id, Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);

            }
            await _unitOfWork.ActorService.UpdateAsync(id, actor);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var atorDetails = await _unitOfWork.ActorService.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            return View(atorDetails);
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var atorDetails = await _unitOfWork.ActorService.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            await _unitOfWork.ActorService.DeleteAsync(id);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }




    }
}

eTickets/Controllers/CinemasController.cs
using eTickets.Data;
using eTickets.Data.Base.BaesInterFaces;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CinemasController : Controller
    {
        private readonly IunitOfWork _unitOfWork;

        ///private readonly AppDbContext _context;
        ///public CinemasController(AppDbContext context)
        ///{
        ///    _context = context;
        ///}

        public CinemasController(IunitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [AllowAnonymous]

        public async Task<IActionResult> Index()
        {
            var allCinemas = await _unitOfWork.CinemasServices.GetAllAsync();
            return View(allCinemas);
        }


        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create([Bind("Name,Logo,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);

            }
            await _unitOfWork.CinemasServices.AddAsync(cinema);
            await _unitOfWork.Complete();
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]

        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _unitOfWork.CinemasServices.GetByIdAsync(id);
            if (producerDetails is null)
                return View("NotFound");
            return View(producerDetails);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var atorDetails = await _unitOfWork.CinemasServices.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            return View(atorDetails);
        }
        [HttpPost]

        public async Task<IActionResult> Edit(int id, Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);

            }
            await _unitOfWork.CinemasServices.UpdateAsync(id, cinema);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var atorDetails = await _unitOfWork.CinemasServices.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            return View(atorDetails);
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var atorDetails = await _unitOfWork.CinemasServices.GetByIdAsync(id);
            if (atorDetails is null)
                return View("NotFound");
            await _unitOfWork.CinemasServices.DeleteAsync(id);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

    }
}

eTickets/Controllers/MoviesController.cs
using eTickets.Data;
using eTickets.Data.Base.BaesInterFaces;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        private readonly IunitOfWork _unitOfWork;

        ///private readonly AppDbContext _context;
        ///public MoviesController(AppDbContext context)
        ///{
        ///    _context = context;
        ///}

        public MoviesController(IunitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [AllowAnonymous]

        public async Task<IActionResult> Index()
        {
            var allMovies = await _unitOfWork.MoviesServices.GetAllAsync(n => n.Cinema);
            return View(allMovies);
        }
        //Filter
        [AllowAnonymous]

        public async Task<IActionResult> Filter( string searchString)
        {
            var allMovies = await _unitOfWork.MoviesServices.GetAllAsync(n => n.Cinema);
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allMovies.Where(n=> n.Name.ToLower() .Contains(searchString.ToLower())|| n.Description.ToLower().Contains(searchString.ToLower() ))
                    .ToList();
                return View(nameof(Index), filteredResult);
            }
            return View( nameof(Index), allMovies);
        }
        [AllowAnonymous]

        public async Task<IActionResult> Details(int id)
        {
            var movieDetails = await _unitOfWork.MoviesServices.GetMovieByIdAsync(id);

            return View(movieDetails);
        }


        public async Task<IActionResult> Create()
        {

            var movieDropDownsData = await _unitOfWork.MoviesServices.GetNewMovieDropdownsValues();
            ViewBag.Cinmeas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropDownsData = await _unitOfWork.MoviesServices.GetNewMovieDropdownsValues();
                ViewBag.Cinmeas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
                return View(movie);
            }
            await _unitOfWork.MoviesServices.AddNewMovieAsync(movie);

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Edit(int id)
        {

            var movieDetails = await _unitOfWork.MoviesServices.GetMovieByIdAsync(id);
            if (movieDetails == null) return View("NotFound");
             var responce = new NewMovieVM()
            {
                Id = id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                ImageURL = movieDetails.ImageURL,
                MoiveCategory = movieDetails.MoiveCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerID = movieDetails.ProducerID,
                ActorsIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList()
            };
            var movieDropDownsData = await _unitOfWork.MoviesServices.GetNewMovieDropdownsValues();
            ViewBag.Cinmeas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
            return View(responce);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id ,  NewMovieVM movie)
        {
            if(id != movie.Id) return View(nameof(NotFound));
            if (!ModelState.IsValid)
            {
                var movieDropDownsData = await _unitOfWork.MoviesServices.GetNewMovieDropdownsValues();
                ViewBag.Cinmeas = new SelectList(movieDropDownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropDownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropDownsData.Actors, "Id", "FullName");
                return View(movie);
            }
            await _unitOfWork.MoviesServices.UpdateMovieAsync(movie);

            return RedirectToAction(nameof(Index));
        }

    }
}

eTickets/Controllers/OrdersController.cs
using eTickets.Data.Base.BaesInterFaces;
using eTickets.Data.Cart;
using eTickets.Data.Services.InterFaces;
using eTickets.Data.Static;
using eTickets.Data.ViewModels;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IunitOfWork _unitOfWork;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;

        public OrdersController(IunitOfWork unitOfWork, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _unitOfWork = unitOfWork;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _orderService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();

            _shoppingCart.ShoppingCartItems = items;
            var responce = new ShopingCartVM()
            {
                shoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(responce);
        }


        public async Task<IActionResult> AddToShoppingCart(int id)
        {
            var item = await _unitOfWork.MoviesServices.GetByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddMovieToCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));

        }


        public async Task<IActionResult> RemoveFromShoppingCart(int id)
        {
            var item = await _unitOfWork.MoviesServices.GetByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.removeItemFromCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));

        }

        public async Task<IActionResult> CopmletOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmail = User.FindFirstValue(ClaimTypes.Email);

            await _orderService.storeOrderAsyns(items, userId, userEmail);

            await _shoppingCart.clearShoppingCartAsync();
            

            return View("OrderCompleted");


        }
    }
}

eTickets/Controllers/ProducersController.cs
using eTickets.Data;
using eTickets.Data.Base.BaesInterFaces;
using eTickets.Data.Static;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize(Roles =UserRoles.Admin)]
    public class ProducersController : Controller
    {
        private readonly IunitOfWork _unitOfWork;

        public ProducersController(IunitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        [AllowAnonymous]

        public async Task<IActionResult> Index()
        {
            var AllProducers = await _unitOfWork.ProducerServices.GetAllAsync();
            return View(AllProducers);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);

            }
            await _unitOfWork.ProducerServices.AddAsync(producer);
            await _unitOfWork.Complete();
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]

        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _unitOfWork.ProducerServices.GetByIdAsync(id);
            if (producerDetails is null)
                return View("NotFound");
            return View(producerDetails);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _unitOfWork.ProducerServices.GetByIdAsync(id);
            if (producerDetails is null)
                return View("NotFound");
            return View(producerDetails);
        }
        [HttpPost]

        public async Task<IActionResult> Edit(int id, Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);

            }
            await _unitOfWork.ProducerServices.UpdateAsync(id, producer);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var producerDetails = await _unitOfWork.ProducerServices.GetByIdAsync(id);
            if (producerDetails is null)
                return View("NotFound");
            return View(producerDetails);
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetails = await _unitOfWork.ProducerServices.GetByIdAsync(id);
            if (producerDetails is null)
                return View("NotFound");
            await _unitOfWork.ProducerServices.DeleteAsync(id);
            await _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

    }
}

eTickets/Views/Movies/Create.cshtml
@using eTickets.Data.Enums;
@model NewMovieVM

@{
    ViewData["Title"] = "Create a new Movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new movie</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>


                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="col-md-6">

                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinmeas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="MoiveCategory" class="control-label"></label>
                                <select asp-for="MoiveCategory" class="form-control " asp-items="Html.GetEnumSelectList<MoiveCategory>()"></select>
                                <span asp-validation-for="MoiveCategory" class="text-danger"></span>
                            </div>


                            <div class="form-group">
                                <label asp-for="ProducerID" class="control-label"></label>
                                <select asp-for="ProducerID" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerID" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ActorsIds" class="control-label"></label>
                                <select asp-for="ActorsIds" class="form-control" multiple asp-items="ViewBag.Actors"></select>
                                <span asp-validation-for="ActorsIds" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>

                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn btn-outline-success float-right " />
                        <a class="btn btn-outline-secondary " asp-action="Index">Show all</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById('ImageUrrlPreview');
            output.src = $(this).val();
        })
    </script>
    }

eTickets/Views/Movies/Details.cshtml
@model Movie

@{
    ViewData["Title"] = "Movie Details";
}


<div class="row">

    <div class="col-md-8 offset-2">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name

                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Cinemas" asp-action="Details" asp-route-Id="@Model.CinemaId">
                                @Model.Cinema.Name
                            </a>


                        </p>

                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producers" asp-action="Details" asp-route-Id="@Model.ProducerID">
                                @Model.Producer.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MoiveCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABALE</span>

                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>

                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>

                            }

                        </p>

                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />

                            <div class="row">
                                @foreach (var actor in Model.Actors_Movies)
                                {
                                    <div class="column text-center">
                                        <img class="border rounded-circle" src="@actor.Actor.ProfilePictureURL" style="max-width : 150px" />
                                        <br />
                                        <a asp-controller="Actors" asp-action="Details" asp-route-Id="@actor.ActorId">
                                            @actor.Actor.FullName
                                        </a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer ">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                <i class="fas fa-eye-fill"></i> Back To List
                            </a>

                            <a class="btn btn-success text-white  @((DateTime.Now > Model.EndDate) ? "disabled" : "") "
                            asp-controller="Orders" asp-action="AddToShoppingCart" asp-route-id="@Model.Id">

                                <i class="fas fa-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

eTickets/Views/Movies/Index.cshtml
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "List of Movies";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name

                                    @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"> <i class="fas fa-edit"></i> </a>

                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b>@item.Cinema.Name</p>
                            <p class="card-text"><b>Category: </b>@item.MoiveCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABALE</span>

                                }
                                else if(DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>

                                }
                                else
                                {
                                    <span class="badge bg-primary text-white" >UPCOMING</span>

                                }
                             
                                
                             
                              
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="fas fa-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white  @((DateTime.Now > item.EndDate) ? "disabled" : "")"
                                asp-controller="Orders" asp-action="AddToShoppingCart" asp-route-id="@item.Id">
                               
                                    <i class="fas fa-cart-plus " ></i> Add to Cart (Price @item.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("PartialViews/_CreateItem","Movies")